export enum Config {
  MONGODB_URI = 'MONGODB_URI',
  W3S_KEY = 'W3S_KEY',
  W3S_GATEWAY_URL = 'W3S_GATEWAY_URL',
  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',
  AWS_REGION = 'AWS_REGION',
  S3_BUCKET_NAME = 'S3_BUCKET_NAME',
  LOG_DIR = 'LOG_DIR',
  UPLOAD_FILE_SIZE_LIMIT = 'UPLOAD_FILE_SIZE_LIMIT',
  CORS_ORIGIN_LIST = 'CORS_ORIGIN_LIST'
}
